# Test type conversion functions
print(int(3.14))
print(int(True))
print(int(False))
print(int("42"))
print(float(42))
print(float(True))
print(float("3.14"))
print(str(42))
print(str(3.14))
print(str(True))
print(bool(0))
print(bool(1))
print(bool(""))
print(bool("hello"))
